### ISSUE TITLE
Stop opening of alert in beforeOpen event?

### ISSUE THREAD

**Issue by resting** [toverux/ngx-sweetalert2#37]
I'm trying to prevent swal from opening if nothing is selected.
Here's how I initialize it.
```
          <swal
            #deleteSwal
            text="Are you sure you want to delete the following products?"
            type="question"
            [showCancelButton]="true"
            (confirm)="onDelete()"
            (beforeOpen)="beforeOpenDelete()"
          ></swa>
```

Is it possible to interrupt the opening process in `beforeOpen` event?

**Comment by toverux** [comment]
Unfortunately, no. Because the onBeforeOpen event comes directly from SweetAlert2 and does not provides any way to prevent the modal apparition.
However, you can still handle that before ngx-sweetalert2 is involved, for example:

```html
<button [disabled]="!somethingIsSelected" [swal]="mySwal">Delete</button>
```

should work since the `disabled` state should prevent the `[swal]` directive to intercept the click.

**Comment by resting** [comment]
Cool. Thanks for the confirmation and solution. That works for me :)
